language: node_js

node_js:
  - node

services:
  - docker

before_install:
  - docker build -t timoa/nodejs-encryption-api-example .
  - docker-compose up
  - docker ps -a

script:
    - npm test
    - docker-compose down

notifications:
  email:
    on_success: never
    on_failure: always