language: node_js
node_js:
- node
services:
- docker
before_install:
- docker build -t timoa/nodejs-encryption-api-example .
- docker-compose up -d
- docker ps -a
script:
- npm test
after_script:
  - docker-compose down
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: feature/fix-docker-hub-login
notifications:
  email:
    on_success: never
    on_failure: always