language: node_js

node_js:
  - node

services:
  - docker

before_install:
  - docker build -t timoa/nodejs-encryption-api-example .
  - docker run -d -p 127.0.0.1:3000:3000 timoa/nodejs-encryption-api-example
  - docker-compose up
  - docker ps -a

script:
    - npm test

notifications:
  email:
    on_success: never
    on_failure: always