language: node_js
node_js:
- node
services:
- docker
before_install:
- docker build -t timoa/nodejs-encryption-api-example .
- docker-compose up -d
- docker ps -a
script:
- npm test
after_script:
  - docker-compose down
notifications:
  email:
    on_success: never
    on_failure: always
env:
  matrix:
  - secure: BWDIo7P0wGVOMTUURJZ59QkjGNl9Ch+yJAm/iBZB5NhdZFQ/4NLQ8VaOO6l2psdkjviqrMBOVRUCU6YvKioT3SnIghtApN+YET3ktIHq3ShqQGkXdUQCqSp9Y67hdc0xPoWc/8BcWtd5eXDtSZMLE3pz0FIowvIjd6FJLU170Msij+qX/yWrM3bvc4mpaezaMFJwiDuZrCJgdjTc7peqXOr6ENK5VBRpRp08yZP6xnvN10/TDu5IhzTZeFCKwVhZzi9OiKONF61smcs6xb6WnoVezYXrIMCyf3TedQQfGefswo3s5oomHAPuqlw1ZQHs4LJ4pA1fzK7KQem/2l7D+lUJKNDtdhCc0wpMPyfD2ZuaWhcXmeKrfdjDejGVLr/hXksZD0Yc5RkiXXIz4O0GiC4iydA4FQ8BoayEw/VxUD6MjQd43xOGDTsPQqQ5E1Ly4kqqAdNszK3Fsako2AqNSmN/euE/CkGdsK0Kk12q8p57+uy+fKu08YaMSmHjD5ljjxt+RFEJPpK0/ZOmTBXP8l6C4oCYyqsT6PgmHQ35GbWpe1oTvISiM5Uyz2DwTAFhidSdFBimBMlyK9pBxWSjhICCrm2/LP2dmR5M+09IEBwXrdYagqqDwd3UJOWkbipKC5n8a783BHR1/W1MBaSJH9zKi09KodKJEdywFO6s2gU=
  - secure: e4uafjAGAfe5G1yzjiCvJ6ct9+Us/i/7d/S28prbj4e/4ErjpPZ4hTpiQl0LQ0AV+w9AIHl9ME6Src4aMLReP1L2mZsWP40GsAPpVfTxI0gPIO7XNkL2JJvsIYEnx3dA+m2+XZ+RkHXlaBshXnreHlZFUd/p1lmkfDpgz8JIH9Gh+8EDvzUXLY/0OKh94gkQaNVoiIMdVDj661HJE2UMSgwznF3hho5px1ND5AUynZmdyuOltsY6nWsvf4hDg7CGlc48z6sZoF4VdrTFJLY8Q9Oyh3x4FxIVACgg/XpnRq54ZjKnfQYBX5B51h9kitzm9D3BDg1BGZYq1f868Onk8Gp34sCYFmcRLd00vi/OF3Xv9uRI9GCxt6J8OQMjP/TjwHtuHmSMkB95/NwQOEQGK3sv+ysZyMLAAlqQBCoXVeN/bXZ86jldxeXoey6FsLUFLQAawiHFIYPe3BU/SizjaPm+3HZnDjw7QG0YZo1Vc5kXzeoHXLsrAMWvInueBeJ3991NXeudx5ZWFIhVizwT/RPKzVGUvBTrng5RkwX7KBO78KHM8Iypt+UipPmaPR3LL+IlqHSS3IlAgggkAXAPnRnKqdX7LR3wCytq1DLFR/L+s2I5lT7wKhEom17lTyvd3slRLUpsuBCI7r+Aln7pRg100ueclyToqqSWfEBDPJ0=
