language: node_js
node_js:
- node
services:
- docker
addons:
  sonarcloud:
    organization: timoa-github
before_install:
- docker build -t timoa/nodejs-encryption-api-example .
- docker-compose up -d
- docker ps -a
script:
- npm test
- bash scripts/sonar_scanner.sh
after_script:
- docker-compose down
deploy:
  provider: script
  script: bash scripts/docker_push.sh
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
  - secure: coE3LdddKs6twiRHmZ8fR2EiepXBeHzNJTOyNb9/AnLEgM7jgTutvRDvvA/C2ylMTcMYzjjQjPRQ81F1CDtblvAwJDQZ5GvZXwcMX8N3jLE6Lc7L0PRYtzwCpidsRw3eOpmSbV12WPrHVJtfI9MrzAWn1pittbtpl+ZmcP+dvVWI1y9pS8sRqbvE5U3gPCnKF4h9CzUMgUd/VdXiGkX2Gl0zjw2pUU9/HidJbbVhDJNBhLZxuyee/nufLM9zmUNAmQ5HrQPkd6ONaEnSP1F9N1ntl4xHKQZDfq+IdQcuu948cbujz10RAkxjbED5y8WJijJBhdXvJHMUjoXDPRd+sZXtpYwbpC5VC508TW13oONvhMVU82+hACkKEv7I3mlwLTOniIkIzaIqrGbt/3Q93huXjmCp1OnqdwsiwpXkb1omuu+nPrNxwH8seDWm8EpwCfeq+dDq3tvPvdWTIms7YaG7824VOPl4r0gaxkw5q9BRg/fTP0GtZAJwmxC0U29fBBuIC0Mu7Xv2/Q9w/hjGOv7r6qLDRczGqgtnClVee1OwymOpiEeE95Nk8Skrs7Zz+p5FqIPXPUKUkltV1dVRzeT2/LronsJs9IWxDPeVCFmWvVHDbIV+B7H0G6nH5gYueEHBdIG4g2mJUoXx/iUNGvviHEZklV7GAdL1Np/ao5s=
  - secure: o2GNeodIQkYw68y++8lTuVpx/1DW99XOb7zuMxhc6pZZp6HGUjMLiP73SB/ur3yZpQj1aVDj08Ozj7Av+v1pL6FJkttdYRzY8t8xkW/kSGq0Ht+0jSYEu4AqHK78JuK0Wa9Zrvmq6wK2CJkobSFHX0fok9qr25VNG/yP43cS3wigMRxQM4d3z/VAt9gJAX/WNd1lcLUelZjV5cSZQvmV029rLFBTBieT5C5vMZMFvHxvCPGQg2krgEWc0OFuOxfWw8Tv0kqDqIE5FXfIEWTEhtZMtkQ4HlrC8qjVk2X/TfxaTtJD+xlovYWaZdR3NcDg1dmfIgbiBiYSx3fSZWiSC6xLqDNRL0lTgZ70Ysqj9334szu7GCT4rqQpclclprvu8NL0KR9IgNJ9MMRWM+Vn7y0CmMkZ1dqVrWxl2Xzh0ikQVKoAZXoYO4zlfeeJtIlV3pzE+xAIU77/3CL/QA+DfjU4GvNyNrPhzhOnu1wjLl9lc3dJAvcn3MOMmYAsdtxbRlfz3VN8nbGuUVrTorJcDE/xiFdX/c0zZjKqrLLTLTk80dtbXJ24fcxRDDpLX2QtqNZb7qQCGOCViDQfT+L0heZJpdK+qwvQ9tyHsJGM3HJSl550ZnG93AhTPs7BBwMZJJSJjzRu1xPjseTdZYGYLz3xoettmSE9L4S6rweE+I0=
  - secure: AsfintEH9gIUwQ4B/hdpxcJXuVdODEaXS01UqSGWeXmqtMJRHusq5GNy6UASqLAMGioPuRKU/qBU93slyQw/e6vVF8380dUkijil4ZvRfyvY5WSHiBciTAZRISgMWJ05LzibujOD4jxpoUEFj+MkiiD9x9oKOYiF7RP9Q/DcZ6nQrVabw/I94LOJ3PK5frao1XTe+OeD1JATHoPz9k/UD1g6+6sCK1XzfacPmCGwTgfqpkKHjiJWn5JZL+dIHZ1r3fZ9H481MdPkDmkb5U0kZZas0AjNSd84FgWN8G/jqMq2Mirk7AsIB9DjFI9/SNBGYoxSGkC2nB9FCEIw1AIa0EeprDbrNHjAF8HBIuyf+8f8HUTqIOigcmyE+yYC490TLHMO4+RORCaxFdvX//alEae3I0mPKDi0L0gdAyxs3tM6CY3pt1fU5xj4ct6ii9m+drufmwSBPwI0cOlPnDYKDFuHhoD48KnPxqgESTTf9Fpdh+/PN5UyJAzaSXjNZTVCr+hm7TTTaSsIgx9X0dWVD0SSa3yXKe656cBlx+hr7GuSl/QSGZMffhkJKnnGLGRTW2RtAwwT4jIv/5rMkTtwNesHu7dp9180Dv1wK7el3W8d5+inXJm9tkoBZHTXdZ0k2p5n31Bbrgvmf0p5kxXM4Zy2oF6moqBW5gBe73tDuak=
