language: node_js
node_js:
- node
services:
- docker
addons:
  sonarcloud:
    organization: timoa-github
before_script:
- docker build -t timoa/nodejs-encryption-api-example .
- docker-compose up -d
- docker ps -a
script:
- npm run test:coverage
- npm run test:functional
- bash scripts/sonar_scanner.sh
after_script:
- docker-compose down
deploy:
  provider: script
  script: bash scripts/docker_push.sh
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always