language: node_js
node_js:
- node
services:
- docker
addons:
  sonarcloud:
    organization: "timoa-github"
before_install:
- docker build -t timoa/nodejs-encryption-api-example .
- docker-compose up -d
- docker ps -a
script:
- npm test
- bash sonar_scanner
after_script:
  - docker-compose down
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always