version: '2'

services:
  api:
    image: timoa/nodejs-encryption-api-example:latest
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    restart: always
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
